### ISSUE TITLE
Localization for an Excellent Tool !!!!

### ISSUE THREAD

**Issue by geogerar** [vermont42/JFATabBarController#1]
Hello,
First of all I would like to Thank you for your excellent tool and your nice job.
I want to use your tool in one of my apps I am developing now.
I want to please you if you can to add localization for the labels in tabBarItems like in UITabBarController
"[[tb.tabBar.items objectAtIndex:0] setTitle:[TSLanguageManager localizedString:@"Pulse"]]"

Thank you very much again

George Gerardis

**Comment by vermont42** [comment]
I prefer not to add a third-party dependency for localization. TLLanguageManager looks like a great library, though.
