### ISSUE TITLE
how to use with an navigation controller??

### ISSUE THREAD

**Issue by kunalverma25** [vermont42/JFATabBarController#3]
It hides the navigation controllers of tabs at 5 or more..

**Comment by kunalverma25** [comment]
If anyone else is having this issue.
Please set
navigationController.navigationBarHidden = NO;
in JFATabBarController.m

AANNDDD

add this
self.navigationItem.hidesBackButton = true

in your view controller's view did Load

**Comment by vermont42** [comment]
Thanks, Kunal.
