### ISSUE TITLE
add or remove tabs..

### ISSUE THREAD

**Issue by kunalverma25** [vermont42/JFATabBarController#4]
The icons tabbar itemsdoes not update when items from tabbar are removed.

**Comment by kunalverma25** [comment]
Please add an option to remove tabs. or to refresh the JFATabBar from code after removing items from the underlying tabbar

**Comment by vermont42** [comment]
I would consider a pull request to implement this functionality. But because my app that uses `JFATabBarController`, [Immigration](https://itunes.apple.com/us/app/immigration/id777319358), has no need for adding or removing tabs, I will not implement it myself.
